/**
 *
 */
module.exports = {
  ATTACK: "ATTACK",
  DEFENSE: "DEFENSE",
  HEALING: "HEALING",
  SHUFFLE: "SHUFFLE",
  VIEW_1_CARD: "VIEW_1_CARD",
  STEAL_1_CARD: "STEAL_1_CARD",
  DRAW_1_CARD: "DRAW_1_CARD",
  SWAP_HEALTH: "SWAP_HEALTH",
  BLOCK_SWAP_HEALTH: "BLOCK_SWAP_HEALTH",
};
